server:
  port: 8888

config:
  repository:
    path: ${user.dir}/config-repo

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:${config.repository.path}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
